name: ${CONTAINER_NAME}

services:
    ##############################################################################
    # Terminal
    ##############################################################################
    terminal:
        image: ${TERMINAL_IMAGE_NAME}
        profiles: ["term"]
        container_name: ${CONTAINER_NAME}-env-terminal
        env_file:
            - ../../.env
        command:
            - sh
            - -c
            - |
              [ -n "$$GIT_USER_NAME" ] && git config --global user.name "$$GIT_USER_NAME"
              [ -n "$$GIT_USER_EMAIL" ] && git config --global user.email "$$GIT_USER_EMAIL"
              exec zsh
        stdin_open: true
        tty: true
        working_dir: "/project"
        volumes:
            - ../../:/project
            - ../.cache/.npm/_logs:/root/.npm/_logs
            - ../.cache/.oh-my-zsh/log:/root/.oh-my-zsh/log
            - ../.cache/.config/gh:/root/.config/gh
            - ../.cache/.git:/root/.git
        environment:
            - INSIDE_DEV_WORKSPACE=true
            - HISTFILE=/root/.cache/.zsh_history
            - NPM_CONFIG_CACHE=/root/.cache/.npm
            - COMPOSER_HOME=/root/.cache/.composer
            - GIT_CONFIG_GLOBAL=/root/.git/config
