<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => NULL,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => NULL,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pimple/pimple' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => 'a94b3a4db7fb774b3d78dad2315ddc07629e1bed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pimple/pimple',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '68f5200c33f18c018db17eb869d4b0f97da17cad',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'publishpress/instance-protection' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '4193f84a8a680bf4c0d40cc64976ddcadd92158a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../publishpress/instance-protection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'publishpress/pimple-pimple' => array(
            'pretty_version' => '3.5.0.10',
            'version' => '3.5.0.10',
            'reference' => 'f2784f4b1ccaf195b373a46a74cf3742e7c9f826',
            'type' => 'library',
            'install_path' => __DIR__ . '/../publishpress/pimple-pimple',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'publishpress/psr-container' => array(
            'pretty_version' => '2.0.1.10',
            'version' => '2.0.1.10',
            'reference' => '4ccd2cb058e7b93e96186791ca25870a02e35c5d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../publishpress/psr-container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'publishpress/vendor-locator-revisions' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '54f05c375ca020f7a2b043f0ae2bb8836874ae56',
            'type' => 'library',
            'install_path' => __DIR__ . '/../publishpress/vendor-locator-revisions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'publishpress/wordpress-reviews' => array(
            'pretty_version' => 'v1.1.19',
            'version' => '1.1.19.0',
            'reference' => '028e573eb7c5da2455a7a823cabbbe5e3f89ca9c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../publishpress/wordpress-reviews',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'publishpress/wordpress-version-notices' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'ea8a694f10385275393c3e36b524d40019a591fa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../publishpress/wordpress-version-notices',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
