name: VIP Scans and other code checks
permissions:
  contents: read
on:
  push:
    branches:
      - 'master'
      - 'development'
      - 'release/*'
      - 'release-*'

  pull_request:
    branches:
      - '*'

  workflow_call:

  workflow_dispatch:

jobs:
  check:
    # v2.0.0
    uses: publishpress/github-workflows/.github/workflows/code-check.yml@0f5e3a3488accd905de7b26e9d57364e303837f5
