name: Deploy plugin to WordPress.org
on:
  release:
    types: [ released ]

jobs:
  deploy-wp-org:
    permissions:
      contents: write
    uses: publishpress/github-workflows/.github/workflows/deploy-free.yml@v3
    secrets: inherit