name: Deploy assets/readme to WordPress.org
permissions:
  contents: read
on:
  push:
    branches:
      - 'master'

jobs:
  deploy-to-trunk:
    # v2.0.0
    uses: publishpress/github-workflows/.github/workflows/deploy-free-assets.yml@0f5e3a3488accd905de7b26e9d57364e303837f5
