name: Deploy plugin to WordPress.org
on:
  release:
    types: [ released ]

jobs:
  code-check:
    name: Check the code
    uses: ./.github/workflows/code-check.yml
    secrets: inherit

  deploy-wp-org:
    # v2.0.0
    uses: publishpress/github-workflows/.github/workflows/deploy-free.yml@0f5e3a3488accd905de7b26e9d57364e303837f5
    needs: [code-check]
